/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as ApiUploadthingRouteImport } from './../../src/routes/api/uploadthing'
import { ServerRoute as ApiCheckoutRouteImport } from './../../src/routes/api/checkout'
import { ServerRoute as ApiAuthSplatRouteImport } from './../../src/routes/api/auth.$'

// Create/Update Routes

const rootRoute = createServerRoute()

const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRoute,
} as any)

const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRoute,
} as any)

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/api/checkout' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/checkout']['parentRoute'],
    FileRoutesByPath['/api/checkout']['id'],
    FileRoutesByPath['/api/checkout']['path'],
    FileRoutesByPath['/api/checkout']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/uploadthing' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/uploadthing']['parentRoute'],
    FileRoutesByPath['/api/uploadthing']['id'],
    FileRoutesByPath['/api/uploadthing']['path'],
    FileRoutesByPath['/api/uploadthing']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/auth.$' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/auth/$']['parentRoute'],
    FileRoutesByPath['/api/auth/$']['id'],
    FileRoutesByPath['/api/auth/$']['path'],
    FileRoutesByPath['/api/auth/$']['fullPath'],
    unknown
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesByTo {
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/checkout' | '/api/uploadthing' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/checkout' | '/api/uploadthing' | '/api/auth/$'
  id: '__root__' | '/api/checkout' | '/api/uploadthing' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/api/checkout",
        "/api/uploadthing",
        "/api/auth/$"
      ]
    },
    "/api/checkout": {
      "filePath": "api/checkout.ts"
    },
    "/api/uploadthing": {
      "filePath": "api/uploadthing.ts"
    },
    "/api/auth/$": {
      "filePath": "api/auth.$.ts"
    }
  }
}
ROUTE_MANIFEST_END */
